extraction:
  cpp:
    prepare:
      packages:
        - libprocps-dev
        - libkqueue-dev
        - flex
    configure:
      command:
        - cmake usr/src
    index:
      build_command:
        - make